In [1]:
a * 3


NameError: name 'a' is not defined

In [ ]:
a = 2


In [ ]:
a * 3


6


In [ ]:
a / 3


0.6666666666666666


In [ ]:
a ** 3


8


In [ ]:
a = 2


In [ ]:
a = 2


In [ ]:
a ** 3


8


In [ ]:
a = 2

In [ ]:
a * 3

6


In [ ]:
a / 3

0.6666666666666666


In [ ]:
a ** 3

8


In [ ]:
?a

Traceback (most recent call last):
  File "/Users/pittsburghgraduatestudent/.vscode/extensions/ms-python.python-2024.22.2-darwin-x64/python_files/python_server.py", line 133, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1
    ?a
    ^
SyntaxError: invalid syntax



In [ ]:
a?

Traceback (most recent call last):
  File "/Users/pittsburghgraduatestudent/.vscode/extensions/ms-python.python-2024.22.2-darwin-x64/python_files/python_server.py", line 133, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1
    a?
     ^
SyntaxError: invalid syntax



In [ ]:
a

2


In [ ]:
?a

Traceback (most recent call last):
  File "/Users/pittsburghgraduatestudent/.vscode/extensions/ms-python.python-2024.22.2-darwin-x64/python_files/python_server.py", line 133, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1
    ?a
    ^
SyntaxError: invalid syntax



In [ ]:
a = 2

In [ ]:
a = 2
?a

Traceback (most recent call last):
  File "/Users/pittsburghgraduatestudent/.vscode/extensions/ms-python.python-2024.22.2-darwin-x64/python_files/python_server.py", line 133, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 2
    ?a
    ^
SyntaxError: invalid syntax



In [1]:
a = 2
?a

Type:        int
String form: 2
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating-point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

In [2]:
a?

Type:        int
String form: 2
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating-point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

In [3]:
print(a)

2


In [4]:
%whos

Variable   Type    Data/Info
----------------------------
a          int     2


In [5]:
a + 2

4

In [6]:
a + 2.0

4.0

In [7]:
a / 3

0.6666666666666666

In [8]:
a // 3

0

In [9]:
a // 3.0

0.0

In [10]:
b = sqrt(a)

NameError: name 'sqrt' is not defined

In [12]:
import numpy as np
b = np.sqrt(a)

In [13]:
B

NameError: name 'B' is not defined

In [14]:
b

np.float64(1.4142135623730951)

In [15]:
?np.sqrt


Signature:       np.sqrt(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'sqrt'>
File:            ~/miniforge3/envs/datascience/lib/python3.13/site-packages/numpy/__init__.py
Docstring:      
sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Return the non-negative square-root of an array, element-wise.

Parameters
----------
x : array_like
    The values whose square-roots are required.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `ou

In [16]:
c = 1.5E1

In [17]:
?c

Type:        float
String form: 15.0
Docstring:   Convert a string or number to a floating-point number, if possible.

In [18]:
c = 5 > 3
c
?c

Type:        bool
String form: True
Docstring:  
Returns True when the argument is true, False otherwise.
The builtins True and False are the only two instances of the class bool.
The class bool is a subclass of the class int, and cannot be subclassed.

In [19]:
c = '15'
print(c + '10')

1510


In [20]:
print(c*3)

151515


In [21]:
atup = (1, '20', 3)
?atup

Type:        tuple
String form: (1, '20', 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [22]:
carr = np.array(ctmp)

NameError: name 'ctmp' is not defined

In [26]:
carr = np.array(atup)
?carr

Type:        ndarray
String form: ['1' '20' '3']
Length:      3
File:        ~/miniforge3/envs/datascience/lib/python3.13/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optiona

In [27]:
carr + 1

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [25]:
carr + [1]

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [29]:
carr = np.array(atup)
?carr

Type:        ndarray
String form: ['1' '20' '3']
Length:      3
File:        ~/miniforge3/envs/datascience/lib/python3.13/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optiona

In [3]:
inmport numpy as np
carr = np.array(atup)
?carr

SyntaxError: invalid syntax (1341172401.py, line 1)

In [31]:
import numpy as np
carr = np.array(atup)
?carr

Type:        ndarray
String form: ['1' '20' '3']
Length:      3
File:        ~/miniforge3/envs/datascience/lib/python3.13/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optiona

In [4]:
carr + 1

NameError: name 'carr' is not defined

In [33]:
carr + [1]

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [34]:
np.sqrt(carr)

TypeError: ufunc 'sqrt' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [5]:
ctmp = [1, 20, 3]

In [6]:
import numpy as np
carr = np.array(ctmp)

In [7]:
?carr

Type:        ndarray
String form: [ 1 20  3]
Length:      3
File:        ~/miniforge3/envs/datascience/lib/python3.13/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
  

In [8]:
carr + 1

array([ 2, 21,  4])

In [9]:
carr + [1]

array([ 2, 21,  4])

In [10]:
np.sqrt(carr)

array([1.        , 4.47213595, 1.73205081])

In [11]:
carr.max()

np.int64(20)

In [13]:
carr.min()

np.int64(1)

In [14]:
carr.sum()

np.int64(24)