# Scope Rules #

If you have varibales or functions with the same name, how do we know which variables Python uses at any given time. 

Like imagine if you have two for loops taht all start: for i in list_a: and for i in list_b: , how do we know that one (i) won't mess with the others?


**LEGB**

- L - local (current function you're in)
- E - enclosing function (function that called the current function)
- G - global (module in which function was defined)
- B - built in (Python's Built in Name Space).


**Name Error Exception** - when Python cannot resolve the name -> i.e. it can't find an object that has the name you requested. **Program Stops at This Point**

**You can manipulate global variables from within functions**

**Important Terminology to Remember**:
- Argument: an object that is passed to a function as its input when the function is called.
- Parameter: variable that is used in the function definition to refer to that argument. 

**As Soon as Python Exits a Function - variables created in that function are deleted**


In [6]:
def update():
    x.append(1)


[1, 1, 1]

In [5]:


## Steps Python goes through to find x - Using LEGB Rule ##
# Step 1: Looks for x inside local scope (in this case that means the function: update)
# Step 2: The global layer -> the module or the namespace where the function update was defined.
# The global layer DOES contain an object named x.



[1, 1, 1]

In [ ]:
x=[1,1]
update()
x

In [9]:
def update (n, x): # Scopre Rules Inner Layer of Onion
    n = 2
    x.append(4) # Second line appends number 4 to list we created in main function.
    print("update: ",n,x)

def main(): # Scopre rules middle layer of onion
    n = 1
    x = [0,1,2,3]
    print("main: ", n, x)
    update(n,x) 
    print("main: ", n, x)

main() # Scopre rules outer layer of onion

main:  1 [0, 1, 2, 3]
update:  2 [0, 1, 2, 3, 4]
main:  1 [0, 1, 2, 3, 4]


In [10]:
## Exercises ##

def increment(n):
    n += 1
    print(n)

n = 1
increment(n)
print(n)


2
1


In [11]:
def increment(n):
    n += 1
    return n
    
n = 1
while n < 10:
    n = increment(n)
print(n)

10


# Classes and Object-Oriented Programming #

**Emphasis on functions and functional programming in our class**

Good to know at least SOME basic stuff about classes and object oriented programming. 

**Objects** - consist of internal data and methods that perform operations ont he data.
- When an object of a particular type is created that object is called an **instance of that type.**

You may find that an existing object type doesn't fully suit your needs in which case
you can create a new type of oject known as a **class**.

Even if you need a new object type: it likely resembles other object types in some way.
YOu will need to use **Inheritance** - you can define a new class (object type)
that inherits properties from an existing object type. 

**Self** - Functions defined inside a class are known as "instance methods" because they
operate on an instance of hte class. by convention the name of the class instance
is called **self** and it is always passed as the first argument to the functions
defined as part of a class.



In [11]:
ml = [5,9,3,6,8,11,4,3]
ml.sort()
ml

## How to create a new class (basically a new type of python object)

## BLUE PRINT OF A NEW CLASS - SPECIFIES INTERNAL STRUCTURE of these New Types of Objects ##
## DOES NOT: Create an object of that type. Creates an object that's not an object ##

class MyList(list): # Put list in parentheses - This is how python specifies inheritance. Base class: list. Derived Class My List
                    # MyList can re-define inherited attributes and add new attributes that list didnt have.
        def remove_min(self):
            self.remove(min(self))
        def remove_max(self):
            self.remove(max(self))
            
x = [10,3,5,1,2,7,6,4,8] # Defined a list
y = MyList(x) # Object y is defined and its in "my list" and contains a copy of all of the numbers in x. 
    
dir(x) 

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [10]:
dir(y) # Now methods of remove max and remove min are available. 


['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'remove_max',
 'remove_min',
 'reverse',
 'sort']

In [12]:
y.remove_min() #Min Removed
y

[10, 3, 5, 2, 7, 6, 4, 8]

In [14]:
y.remove_max() # Max Removed
y

[3, 5, 2, 7, 6, 4]

In [15]:
class NewList(list):
    def remove_max(self):
        self.remove(max(self))
    def append_sum(self):
        self.append(sum(self))

x = NewList([1,2,3])
while max(x) < 10:
    x.remove_max()
    x.append_sum()

print(x)


KeyboardInterrupt: 

# Introduction to Numpy Arrays #

**Numpy** - python modules designed for scientific computation.
- Provides tools to integrate your code with existing C, C++, and Fortran code.

**Numpy Arrays** - an additional data type provided by NumPy 
- Used for representing vectors and matricies. 
- Are not dynamically growing -> have a fixed size when they are constructed.
- All elements of the same data type. 
- Default: elements are floating point numbers.

In [16]:
import numpy as np # Industry standard way to import numpy.

zero_vector = np.zeros(5) # Zero vector function - creates a vector full of zeros.

zero_matrix = np.zeros((5,3)) # When you parse in a touple: first argument number of rows. Second is number of collumns.

zero_vector

array([0., 0., 0., 0., 0.])

In [17]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

TO create an empty array use the **np.empty** funciton. 
- Allocates requested space fo rthe array, but does not initialize it!
    - Saves computation time, but whatever is in the memory space when this gets allocated stays there!
    
**np.array** used to construct arrays using specified numbers. 

In [21]:
x = np.array([1,2,3])

y = np.array([2,4,6]) # Elements of each row is a list. 

A = np.array([[1,3], [5,9]])
A

array([[1, 3],
       [5, 9]])

In [22]:
A.transpose()

array([[1, 5],
       [3, 9]])

In [23]:
## Exercises ##

import numpy as np

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros(0,0,0,0,0)

TypeError: zeros() takes at most 3 arguments (5 given)

In [26]:
import numpy 
x = numpy.array([[3,6],[5,7]])
y = x.transpose()
print(y)


[[3 5]
 [6 7]]


# Slicing Numpy Arrays #

In [27]:
x = np.array([1,2,3])
y = np.array([2,4,6])

X = np.array([[1,2,3], [4,5,6]])
Y = np.array([[2,4,6], [8,10,12]])

x[2] # -> gives element of x


3

In [28]:
# SLicing start and stop elements 

x[0:2]

array([1, 2])

In [29]:
z = x + y # Element-wise additions of x and y. 

In [30]:
z

array([3, 6, 9])

In [31]:
X[:,1] # First collumn of array X (remember python index starts at zero.


array([2, 5])

In [32]:
Y[:,1]

array([ 4, 10])

In [33]:
X[:,1] + Y[:,1]

array([ 6, 15])

In [37]:
X[1,:]  # Gives you all elements of the first row of array (again elements start at zero).

array([4, 5, 6])

In [38]:
X[1] # First row of X array -> shorthand

array([4, 5, 6])

In [39]:
## Remember adding two lists CONCATENATES THE LISTS. WHAT HAPPENS WHEN WE turn those lists into a numpy array.

In [41]:
np.array([2,4]) + np.array([6,8]) ## Item by item addition over here.

array([ 8, 12])

In [45]:
## Exercises ##
x = np.array([1,2,5])
x[0:3]

a = np.array([1,2])
b = np.array([3,4,5])
a + b


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

# Indexing Numpy Arrays #
NuMpy arrayes can also be indexed with other arrays or other sequence like objects like lists

In [2]:
import numpy as np
z1 = np.array([1,3,5,7,9])
z2 = z1 + 1
z1

array([1, 3, 5, 7, 9])

In [3]:
z2

array([ 2,  4,  6,  8, 10])

In [4]:
# A list to index z1 and z2 called ind:

ind = [0,2,3]
z1[ind] #Allows access to elements of z1 at locations specified by ind

array([1, 5, 7])

In [6]:
# Can also define ind as an np.array
ind = np.array([0,2,3])
z1[ind]

array([1, 5, 7])

**Arrays of Booleans (True/False)**

In [8]:
z1 = np.array([1,3,5,7,9])
z1>6 # Tells you which elements in the array are greater than 6

array([False, False, False,  True,  True])

In [10]:
z1[z1 > 6] # Returns elements of the array that are greater than 6

array([7, 9])

In [11]:
# NOW SWITCH IT UP TO Z2 (defined above)

z2[z1 > 6] # -> the indeces of z1 that contained values greater than 6 are used
           # to return values from z2


array([ 8, 10])

**Logical Vectors** -> numpy specific 

**Vectors** - like arrays: they hold multiple number values


**Logical Vector** - a vector that has only TRUE or FALSE values

In [13]:
# Explicityl constructing LOGICAL vector
ind = z1 > 6
ind

array([False, False, False,  True,  True])

**IMPORTANT NOTE ON NP.ARRAY SLICING**

When you slice a numpy array you get a "view of the object". If you modify it, you modify the origina ojbect.

**In conventional arrays** you just get a copy of that obejct so you don't have to worry about it.

**This weird np.array rule only applies to slicing and not indexing.**

In [15]:
z1 = np.array([1,3,5,7,9])
w = z1[0:3] # New array that is slice of np.array z1

In [16]:
w[0] = 3

In [17]:
z1 # Note how the first of the array z1 is also modified!

array([3, 3, 5, 7, 9])

In [18]:
# EXERCISES #

a = np.array([1,2])
b = np.array([3,4,5])
b[a]

array([4, 5])

In [20]:
c = b[1:]
c

array([4, 5])

# Building and Examining NumPy Arrays #

In [2]:
import numpy as np
np.linspace(0, 100, 10) # start, end, delta

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [3]:
# Constructing 10 logarithmically spaced 
# elements between 10 and 100


#Uniformly spaced in the logarithmic space.
np.logspace(1,2,10) # log of starting point (log(10) = 1), log of second element, number of elements

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [4]:
# log space even numbers between 250 and 500
# first take the base 10 log of 250 and 500

np.logspace(np.log10(250), np.log10(500), 10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

**Array Explanation Area**

In [6]:
X = np.array([[1,2,3], [4,5,6]])
X.shape #Shape of the array

(2, 3)

In [8]:
X.size # Number of elements in array

6

**Why you don't have parentheses around shape and size** - shape and size are data attributes not methods of the arrays. 

In [15]:
x = np.random.random(10) #Generates 10 random nums
x

array([0.27112402, 0.25237571, 0.58471113, 0.92733179, 0.63519192,
       0.86422371, 0.40096179, 0.91467435, 0.9243974 , 0.21865594])

In [16]:
np.any(x > 0.9) # Checks if any of the elements of the array x are greater than 0.9

True

In [17]:
np.all(x >= 0.1) #If all elements of the array are greater than 0.1

True

In [18]:
# Exercises #

In [24]:
x = 20
not np.any([x%i == 0 for i in range(2, x)])
# Code intepretation: array checks if x / i will have a
# have a remainder of 0. Retruns true if any number
# returns true. So if 20%2 == 0 we're good! 
# The np.any function returns true.

# BUT THERE IS A NOT! So in case its an even number
# we return false. In case its an odd number we return 
# true. The range function is there to confuse you. 

for i in range(2,x):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
